name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Copy kubeconfig
      run: |
        mkdir ~/.kube
        cp .github/workflows/assets/placeholder-kubeconfig.yaml ~/.kube/config
    - name: test
      run: make test

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build-linux
      run: make
    - name: build-windows
      run: make windows
    - name: build-darwin
      run: make darwin

