name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: test
      run: make test

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build-linux
      run: make
    - name: build-windows
      run: make windows
    - name: build-darwin
      run: make darwin

